### ISSUE TITLE
Retrieve an input with unexpanded variables

### ISSUE THREAD

**Issue by sandorfr** [Microsoft/vsts-task-lib#124]
I wonder if there is an undocumented way to retrieve a task input without variable being expanded.

The use case is that I have a JSON input. Users might use variable to adjust that json values, but variable must be escaped during replacement. (more details [here](https://github.com/geeklearningio/gl-vsts-tasks-file-patch/issues/4))

There are several ways to perform this :
- Performing the replacement myself but I need a way to retrieve raw input
- Adding a custom syntax (such as  `#(VariableName)`) to my task (not a big fan of this approach)
- Having a way to provide custom formatting filters to VSTS such as `$(VariableName:formatter(args))` or `$(VariableName | formatter:args)` and in that case I would provide a jsonEscape filter.`$(VariableName:jsonEscape)`

Let me know what you think.
Regards

**Comment by bryanmacfarlane** [comment]
Nope.  No way right now via the lib as the variables are expanded way before it gets to the lib.

**Comment by sandorfr** [comment]
@bryanmacfarlane  Will this be taken under consideration. Since you closed it immediately, it looks like a no.

**Comment by bryanmacfarlane** [comment]
It's something that we will think about with upcoming feature work.  But, it can't be fixed in the lib because that data is replaced upstream way before it gets to the lib.

**Comment by ericsciple** [comment]
@sandorfr i'm curious if a dictionary input would be an alternate solution for your issue? not full json, but a single-level dictionary.

**Comment by sandorfr** [comment]
@ericsciple dictionary input would be a great addition, but it wouldn't solve this specific issue.

**Comment by sandorfr** [comment]
@bryanmacfarlane since vsts agent is now open sourced, I was wondering if a pull request adding the ability to retrieve unescaped variables would be accepted.

**Comment by ericsciple** [comment]
That approach would put the burden on each task author to solve, and lead to inconsistent approaches.

If a one-level dictionary input doesn't solve, then this sounds like something that might better be solved by allowing functions to be inlined in the task inputs (burden on agent to evaluate).

**Comment by sandorfr** [comment]
@ericsciple not sure to understand `allowing functions to be inlined in the task inputs` what it means, but if it means that the extensions could provide a function to process variables which  would be executed by the agent it would be great. This is why I was suggesting something like this:

> Having a way to provide custom formatting filters to VSTS such as $(VariableName:formatter(args)) or $(VariableName | formatter:args) and in that case I would provide a jsonEscape filter.$(VariableName:jsonEscape)

On a broader point of view, I think we shouldn't  need this extension for basic variable operation https://marketplace.visualstudio.com/items?itemName=jessehouwing.jessehouwing-vsts-variable-tasks#overview
